// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhmpqqemuwbhazsxbcib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFobXBxcWVtdXdiaGF6c3hiY2liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MTU2NzYsImV4cCI6MjA5MDM5MTY3Nn0.IcpRFX9qd_ge7BuRShbJ3EWBvZ4immYcUO4ww3Bri8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});